### ISSUE TITLE
different view

### ISSUE THREAD

**Issue by betterze** [genforce/higan#2]
Thank you for your good work. 

Would you mind telling me which boundary you are using for changing viewpoint? (carpet, clutttered_space, dirt, glossy, indoor_lighting, scary, wood)

Thank you for your help.

**Comment by ShenYujun** [comment]
Thank you for liking our work. The viewpoint boundary and category-related boundaries are not released right now. We will release them in the near future.

**Comment by 250906461** [comment]
Get it, thx

**Comment by betterze** [comment]
Get it, thx.
