### ISSUE TITLE
Where is the stylegan_bedroom/boundary_list.txt?

### ISSUE THREAD

**Issue by flyywh** [genforce/higan#7]
I hope to retrain the models, but I cannot find the existence of BOUNDARY_LIST=stylegan_bedroom/boundary_list.txt. Thanks!

**Comment by limbo0000** [comment]
Hi @flyywh , you have to prepare the boundary list by your own, which looks like 
```
(indoor_lighting, w): boundaries/stylegan_bedroom/indoor_lighting_boundary.npy
(wood, w): boundaries/stylegan_bedroom/wood_boundary.npy

**Comment by flyywh** [comment]
Thanks for you so quick reply!

But In the step 3: 
"Step-3: Rescore to identity the most relevant semantics
Use following command to conduct the layer-wise analaysis and identify relevant semantics:
BOUNDARY_LIST=stylegan_bedroom/boundary_list.txt"

The the boundary list looks like a txt?

**Comment by limbo0000** [comment]
Yes, it is a txt file containing the attribute name, latent space and the path of the boundaries.

**Comment by flyywh** [comment]
Oh, understand! Thanks a lot!
